# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra"
gem "activerecord"
gem "json"
gem 'sinatra-contrib'
gem 'open-uri'
gem 'uri'
gem 'sqlite3'
gem 'webrick'
# gem "rails"
